# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'cmr_bt1.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import image_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1921, 1885)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 1921, 1001))
        self.widget.setStyleSheet(u"background-color: rgb(9, 9, 9);")
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-3, 0, 1921, 991))
        self.label.setFrameShape(QFrame.NoFrame)
        self.label.setPixmap(QPixmap(u"datas/images/ful0.png"))
        self.label.setScaledContents(True)
        self.dragCamBase = QWidget(self.widget)
        self.dragCamBase.setObjectName(u"dragCamBase")
        self.dragCamBase.setGeometry(QRect(20, 60, 411, 311))
        self.dragCamBase.setStyleSheet(u"background-color: rgb(0, 52, 63);")
        self.label_2 = QLabel(self.dragCamBase)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 411, 311))
        self.label_2.setPixmap(QPixmap(u"datas/images/cut_map1.png"))
        self.label_2.setScaledContents(True)
        self.label_3 = QLabel(self.dragCamBase)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(126, 24, 161, 21))
        self.label_3.setStyleSheet(u"background-color: rgb(0, 68, 97);\n"
"font: 25pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);")
        self.showRealtime = QPushButton(self.widget)
        self.showRealtime.setObjectName(u"showRealtime")
        self.showRealtime.setGeometry(QRect(40, 20, 71, 32))
        self.showRealtime.setAutoFillBackground(False)
        self.showRealtime.setStyleSheet(u"")
        icon = QIcon()
        icon.addFile(u"datas/images/bt00006.png", QSize(), QIcon.Active, QIcon.On)
        self.showRealtime.setIcon(icon)
        self.showRealtime.setIconSize(QSize(71, 32))
        self.showRealtime.setCheckable(False)
        self.showRealtime.setAutoDefault(False)
        self.showRealtime.setFlat(False)
        self.showReplay_2 = QPushButton(self.widget)
        self.showReplay_2.setObjectName(u"showReplay_2")
        self.showReplay_2.setGeometry(QRect(200, 20, 71, 32))
        self.showReplay_2.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u"datas/images/bt00003.png", QSize(), QIcon.Active, QIcon.On)
        self.showReplay_2.setIcon(icon1)
        self.showReplay_2.setIconSize(QSize(71, 32))
        self.showReplay = QPushButton(self.widget)
        self.showReplay.setObjectName(u"showReplay")
        self.showReplay.setGeometry(QRect(120, 20, 71, 32))
        self.showReplay.setFocusPolicy(Qt.WheelFocus)
        self.showReplay.setContextMenuPolicy(Qt.PreventContextMenu)
        self.showReplay.setLayoutDirection(Qt.LeftToRight)
        self.showReplay.setAutoFillBackground(False)
        self.showReplay.setStyleSheet(u"")
        icon2 = QIcon()
        iconThemeName = u"Records"
        if QIcon.hasThemeIcon(iconThemeName):
            icon2 = QIcon.fromTheme(iconThemeName)
        else:
            icon2.addFile(u"datas/images/bt00005.png", QSize(), QIcon.Active, QIcon.On)
        
        self.showReplay.setIcon(icon2)
        self.showReplay.setIconSize(QSize(71, 32))
        self.showReplay.setCheckable(False)
        self.showReplay.setChecked(False)
        self.showReplay.setAutoRepeat(False)
        self.showReplay.setAutoExclusive(False)
        self.showReplay.setAutoDefault(True)
        self.showReplay.setFlat(True)
        self.showReplay.setProperty("tabletTracking", True)
        self.widget_8 = QWidget(self.widget)
        self.widget_8.setObjectName(u"widget_8")
        self.widget_8.setGeometry(QRect(20, 560, 411, 341))
        self.widget_8.setStyleSheet(u"background-color: rgb(0, 54, 66);")
        self.label_4 = QLabel(self.widget_8)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 0, 411, 341))
        self.label_4.setPixmap(QPixmap(u"datas/images/cut_map1.png"))
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(self.widget_8)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(126, 30, 167, 21))
        self.label_5.setStyleSheet(u"background-color: rgb(0, 68, 97);\n"
"font: 18pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);")
        self.calendarWidget = QCalendarWidget(self.widget_8)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(10, 70, 391, 121))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 52, 63, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(69, 70, 73, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(57, 58, 61, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(23, 23, 24, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(30, 31, 32, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        brush8 = QBrush(QColor(46, 47, 49, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.calendarWidget.setPalette(palette)
        font = QFont()
        font.setFamily(u"Agency FB")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setFocusPolicy(Qt.NoFocus)
        self.calendarWidget.setContextMenuPolicy(Qt.PreventContextMenu)
        self.calendarWidget.setAcceptDrops(True)
        self.calendarWidget.setLayoutDirection(Qt.LeftToRight)
        self.calendarWidget.setStyleSheet(u"background-color: rgb(0, 52, 63);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 8pt \"Agency FB\";")
        self.calendarWidget.setLocale(QLocale(QLocale.English, QLocale.AmericanSamoa))
        self.calendarWidget.setInputMethodHints(Qt.ImhNone)
        self.calendarWidget.setSelectedDate(QDate(2021, 12, 26))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setSelectionMode(QCalendarWidget.NoSelection)
        self.calendarWidget.setVerticalHeaderFormat(QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.cmr_listWidget_5 = QListWidget(self.widget_8)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        QListWidgetItem(self.cmr_listWidget_5)
        self.cmr_listWidget_5.setObjectName(u"cmr_listWidget_5")
        self.cmr_listWidget_5.setGeometry(QRect(10, 193, 391, 141))
        font1 = QFont()
        font1.setFamily(u"Agency FB")
        font1.setPointSize(14)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setWeight(50)
        self.cmr_listWidget_5.setFont(font1)
        self.cmr_listWidget_5.setStyleSheet(u"background-color: rgb(0, 12, 23);\n"
"font: 14pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.widget_6 = QWidget(self.widget)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(330, 945, 1231, 51))
        self.widget_6.setStyleSheet(u"background-color: rgb(0, 10, 20);")
        self.functionBt_06 = QPushButton(self.widget_6)
        self.functionBt_06.setObjectName(u"functionBt_06")
        self.functionBt_06.setGeometry(QRect(462, 0, 55, 48))
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(False)
        font2.setItalic(False)
        font2.setWeight(50)
        self.functionBt_06.setFont(font2)
        self.functionBt_06.setStyleSheet(u"background-color: rgb(147, 147, 147);")
        icon3 = QIcon()
        icon3.addFile(u"datas/images/13.png", QSize(), QIcon.Normal, QIcon.Off)
        self.functionBt_06.setIcon(icon3)
        self.functionBt_06.setIconSize(QSize(55, 48))
        self.functionBt_05 = QPushButton(self.widget_6)
        self.functionBt_05.setObjectName(u"functionBt_05")
        self.functionBt_05.setGeometry(QRect(369, 0, 55, 48))
        self.functionBt_05.setFont(font2)
        self.functionBt_05.setStyleSheet(u"background-color: rgb(180, 180, 180);")
        icon4 = QIcon()
        icon4.addFile(u"datas/images/10.png", QSize(), QIcon.Normal, QIcon.Off)
        self.functionBt_05.setIcon(icon4)
        self.functionBt_05.setIconSize(QSize(55, 48))
        self.functionBt_04 = QPushButton(self.widget_6)
        self.functionBt_04.setObjectName(u"functionBt_04")
        self.functionBt_04.setGeometry(QRect(280, 0, 55, 48))
        self.functionBt_04.setFont(font2)
        self.functionBt_04.setStyleSheet(u"background-color: rgb(180, 180, 180);")
        icon5 = QIcon()
        icon5.addFile(u"datas/images/7_1.png", QSize(), QIcon.Normal, QIcon.Off)
        self.functionBt_04.setIcon(icon5)
        self.functionBt_04.setIconSize(QSize(55, 48))
        self.functionBt_07 = QPushButton(self.widget_6)
        self.functionBt_07.setObjectName(u"functionBt_07")
        self.functionBt_07.setGeometry(QRect(554, 0, 55, 48))
        self.functionBt_07.setFont(font2)
        self.functionBt_07.setStyleSheet(u"background-color: rgb(147, 147, 147);")
        icon6 = QIcon()
        icon6.addFile(u"datas/images/Ado.jpeg", QSize(), QIcon.Active, QIcon.On)
        self.functionBt_07.setIcon(icon6)
        self.functionBt_07.setIconSize(QSize(55, 48))
        self.functionBt_08 = QPushButton(self.widget_6)
        self.functionBt_08.setObjectName(u"functionBt_08")
        self.functionBt_08.setGeometry(QRect(645, 0, 55, 48))
        self.functionBt_08.setFont(font2)
        self.functionBt_08.setStyleSheet(u"background-color: rgb(147, 147, 147);")
        self.functionBt_08.setIcon(icon6)
        self.functionBt_08.setIconSize(QSize(55, 48))
        self.functionBt_10 = QPushButton(self.widget_6)
        self.functionBt_10.setObjectName(u"functionBt_10")
        self.functionBt_10.setGeometry(QRect(826, 0, 55, 48))
        self.functionBt_10.setFont(font2)
        self.functionBt_10.setStyleSheet(u"background-image: url(:/icons/images/Ado.jpeg);")
        self.functionBt_10.setIcon(icon6)
        self.functionBt_10.setIconSize(QSize(55, 48))
        self.functionBt_09 = QPushButton(self.widget_6)
        self.functionBt_09.setObjectName(u"functionBt_09")
        self.functionBt_09.setGeometry(QRect(735, 0, 55, 48))
        self.functionBt_09.setFont(font2)
        self.functionBt_09.setStyleSheet(u"background-color: rgb(147, 147, 147);")
        self.functionBt_09.setIcon(icon6)
        self.functionBt_09.setIconSize(QSize(55, 48))
        self.functionBt_02 = QPushButton(self.widget_6)
        self.functionBt_02.setObjectName(u"functionBt_02")
        self.functionBt_02.setGeometry(QRect(104, 0, 55, 48))
        self.functionBt_02.setFont(font2)
        self.functionBt_02.setStyleSheet(u"background-color: rgb(180, 180, 180);")
        icon7 = QIcon()
        icon7.addFile(u"datas/images/6.png", QSize(), QIcon.Normal, QIcon.Off)
        self.functionBt_02.setIcon(icon7)
        self.functionBt_02.setIconSize(QSize(55, 48))
        self.functionBt_02.setAutoDefault(False)
        self.functionBt_01 = QPushButton(self.widget_6)
        self.functionBt_01.setObjectName(u"functionBt_01")
        self.functionBt_01.setGeometry(QRect(20, 0, 55, 48))
        font3 = QFont()
        font3.setPointSize(24)
        font3.setBold(False)
        font3.setItalic(False)
        font3.setWeight(50)
        self.functionBt_01.setFont(font3)
        self.functionBt_01.setStyleSheet(u"")
        icon8 = QIcon()
        icon8.addFile(u"datas/images/32.png", QSize(), QIcon.Active, QIcon.On)
        self.functionBt_01.setIcon(icon8)
        self.functionBt_01.setIconSize(QSize(55, 48))
        self.functionBt_03 = QPushButton(self.widget_6)
        self.functionBt_03.setObjectName(u"functionBt_03")
        self.functionBt_03.setGeometry(QRect(190, 0, 55, 48))
        self.functionBt_03.setFont(font2)
        self.functionBt_03.setLayoutDirection(Qt.LeftToRight)
        self.functionBt_03.setStyleSheet(u"background-color: rgb(180, 180, 180);")
        icon9 = QIcon()
        icon9.addFile(u"datas/images/7.png", QSize(), QIcon.Normal, QIcon.Off)
        self.functionBt_03.setIcon(icon9)
        self.functionBt_03.setIconSize(QSize(55, 48))
        self.timeedit = QLabel(self.widget_6)
        self.timeedit.setObjectName(u"timeedit")
        self.timeedit.setGeometry(QRect(910, 0, 321, 51))
        self.timeedit.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(1, 255, 255);\n"
"font: 30pt \"Agency FB\";")
        self.timeedit.setAlignment(Qt.AlignCenter)
        self.widget_3 = QWidget(self.widget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(450, 70, 1460, 850))
        self.widget_3.setStyleSheet(u"background-color: rgb(0, 47, 57);")
        self.ca_widget_01 = QWidget(self.widget_3)
        self.ca_widget_01.setObjectName(u"ca_widget_01")
        self.ca_widget_01.setGeometry(QRect(5, 0, 240, 138))
        self.ca_widget_01.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_01 = QLabel(self.ca_widget_01)
        self.ca_label_01.setObjectName(u"ca_label_01")
        self.ca_label_01.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_01.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_01.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_01.setScaledContents(True)
        self.ca_widget_02 = QWidget(self.widget_3)
        self.ca_widget_02.setObjectName(u"ca_widget_02")
        self.ca_widget_02.setGeometry(QRect(245, 0, 240, 138))
        self.ca_widget_02.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_02 = QLabel(self.ca_widget_02)
        self.ca_label_02.setObjectName(u"ca_label_02")
        self.ca_label_02.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_02.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_02.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_02.setScaledContents(True)
        self.ca_widget_03 = QWidget(self.widget_3)
        self.ca_widget_03.setObjectName(u"ca_widget_03")
        self.ca_widget_03.setGeometry(QRect(485, 0, 240, 138))
        self.ca_widget_03.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_03 = QLabel(self.ca_widget_03)
        self.ca_label_03.setObjectName(u"ca_label_03")
        self.ca_label_03.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_03.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_03.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_03.setScaledContents(True)
        self.ca_widget_04 = QWidget(self.widget_3)
        self.ca_widget_04.setObjectName(u"ca_widget_04")
        self.ca_widget_04.setGeometry(QRect(725, 0, 240, 138))
        self.ca_widget_04.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_04 = QLabel(self.ca_widget_04)
        self.ca_label_04.setObjectName(u"ca_label_04")
        self.ca_label_04.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_04.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_04.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_04.setScaledContents(True)
        self.ca_widget_05 = QWidget(self.widget_3)
        self.ca_widget_05.setObjectName(u"ca_widget_05")
        self.ca_widget_05.setGeometry(QRect(965, 0, 240, 138))
        self.ca_widget_05.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_05 = QLabel(self.ca_widget_05)
        self.ca_label_05.setObjectName(u"ca_label_05")
        self.ca_label_05.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_05.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_05.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_05.setScaledContents(True)
        self.ca_widget_06 = QWidget(self.widget_3)
        self.ca_widget_06.setObjectName(u"ca_widget_06")
        self.ca_widget_06.setGeometry(QRect(1205, 0, 240, 138))
        self.ca_widget_06.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_06 = QLabel(self.ca_widget_06)
        self.ca_label_06.setObjectName(u"ca_label_06")
        self.ca_label_06.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_06.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_06.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_06.setScaledContents(True)
        self.ca_widget_09 = QWidget(self.widget_3)
        self.ca_widget_09.setObjectName(u"ca_widget_09")
        self.ca_widget_09.setGeometry(QRect(484, 138, 240, 138))
        self.ca_widget_09.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_09 = QLabel(self.ca_widget_09)
        self.ca_label_09.setObjectName(u"ca_label_09")
        self.ca_label_09.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_09.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_09.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_09.setScaledContents(True)
        self.ca_widget_11 = QWidget(self.widget_3)
        self.ca_widget_11.setObjectName(u"ca_widget_11")
        self.ca_widget_11.setGeometry(QRect(964, 138, 240, 138))
        self.ca_widget_11.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_11 = QLabel(self.ca_widget_11)
        self.ca_label_11.setObjectName(u"ca_label_11")
        self.ca_label_11.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_11.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_11.setScaledContents(True)
        self.ca_widget_12 = QWidget(self.widget_3)
        self.ca_widget_12.setObjectName(u"ca_widget_12")
        self.ca_widget_12.setGeometry(QRect(1204, 138, 240, 138))
        self.ca_widget_12.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_12 = QLabel(self.ca_widget_12)
        self.ca_label_12.setObjectName(u"ca_label_12")
        self.ca_label_12.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_12.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_12.setScaledContents(True)
        self.ca_widget_08 = QWidget(self.widget_3)
        self.ca_widget_08.setObjectName(u"ca_widget_08")
        self.ca_widget_08.setGeometry(QRect(244, 138, 240, 138))
        self.ca_widget_08.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_08 = QLabel(self.ca_widget_08)
        self.ca_label_08.setObjectName(u"ca_label_08")
        self.ca_label_08.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_08.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_08.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_08.setScaledContents(True)
        self.ca_label_08.raise_()
        self.replayWidget.raise_()
        self.ca_widget_10 = QWidget(self.widget_3)
        self.ca_widget_10.setObjectName(u"ca_widget_10")
        self.ca_widget_10.setGeometry(QRect(724, 138, 240, 138))
        self.ca_widget_10.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_10 = QLabel(self.ca_widget_10)
        self.ca_label_10.setObjectName(u"ca_label_10")
        self.ca_label_10.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_10.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_10.setScaledContents(True)
        self.ca_widget_07 = QWidget(self.widget_3)
        self.ca_widget_07.setObjectName(u"ca_widget_07")
        self.ca_widget_07.setGeometry(QRect(4, 138, 240, 138))
        self.ca_widget_07.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_07 = QLabel(self.ca_widget_07)
        self.ca_label_07.setObjectName(u"ca_label_07")
        self.ca_label_07.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_07.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_07.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_07.setScaledContents(True)
        self.ca_widget_15 = QWidget(self.widget_3)
        self.ca_widget_15.setObjectName(u"ca_widget_15")
        self.ca_widget_15.setGeometry(QRect(484, 276, 240, 138))
        self.ca_widget_15.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_15 = QLabel(self.ca_widget_15)
        self.ca_label_15.setObjectName(u"ca_label_15")
        self.ca_label_15.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_15.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_15.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_15.setScaledContents(True)
        self.ca_widget_17 = QWidget(self.widget_3)
        self.ca_widget_17.setObjectName(u"ca_widget_17")
        self.ca_widget_17.setGeometry(QRect(964, 276, 240, 138))
        self.ca_widget_17.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_17 = QLabel(self.ca_widget_17)
        self.ca_label_17.setObjectName(u"ca_label_17")
        self.ca_label_17.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_17.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_17.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_17.setScaledContents(True)
        self.ca_widget_18 = QWidget(self.widget_3)
        self.ca_widget_18.setObjectName(u"ca_widget_18")
        self.ca_widget_18.setGeometry(QRect(1204, 276, 240, 138))
        self.ca_widget_18.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_18 = QLabel(self.ca_widget_18)
        self.ca_label_18.setObjectName(u"ca_label_18")
        self.ca_label_18.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_18.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_18.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_18.setScaledContents(True)
        self.ca_widget_14 = QWidget(self.widget_3)
        self.ca_widget_14.setObjectName(u"ca_widget_14")
        self.ca_widget_14.setGeometry(QRect(244, 276, 240, 138))
        self.ca_widget_14.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_14 = QLabel(self.ca_widget_14)
        self.ca_label_14.setObjectName(u"ca_label_14")
        self.ca_label_14.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_14.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_14.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_14.setScaledContents(True)
        self.ca_widget_16 = QWidget(self.widget_3)
        self.ca_widget_16.setObjectName(u"ca_widget_16")
        self.ca_widget_16.setGeometry(QRect(724, 276, 240, 138))
        self.ca_widget_16.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_16 = QLabel(self.ca_widget_16)
        self.ca_label_16.setObjectName(u"ca_label_16")
        self.ca_label_16.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_16.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_16.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_16.setScaledContents(True)
        self.ca_widget_13 = QWidget(self.widget_3)
        self.ca_widget_13.setObjectName(u"ca_widget_13")
        self.ca_widget_13.setGeometry(QRect(4, 276, 240, 138))
        self.ca_widget_13.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_13 = QLabel(self.ca_widget_13)
        self.ca_label_13.setObjectName(u"ca_label_13")
        self.ca_label_13.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_13.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_13.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_13.setScaledContents(True)
        self.ca_widget_21 = QWidget(self.widget_3)
        self.ca_widget_21.setObjectName(u"ca_widget_21")
        self.ca_widget_21.setGeometry(QRect(485, 414, 240, 138))
        self.ca_widget_21.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_21 = QLabel(self.ca_widget_21)
        self.ca_label_21.setObjectName(u"ca_label_21")
        self.ca_label_21.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_21.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_21.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_21.setScaledContents(True)
        self.ca_widget_23 = QWidget(self.widget_3)
        self.ca_widget_23.setObjectName(u"ca_widget_23")
        self.ca_widget_23.setGeometry(QRect(965, 414, 240, 138))
        self.ca_widget_23.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_23 = QLabel(self.ca_widget_23)
        self.ca_label_23.setObjectName(u"ca_label_23")
        self.ca_label_23.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_23.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_23.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_23.setScaledContents(True)
        self.ca_widget_24 = QWidget(self.widget_3)
        self.ca_widget_24.setObjectName(u"ca_widget_24")
        self.ca_widget_24.setGeometry(QRect(1205, 414, 240, 138))
        self.ca_widget_24.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_24 = QLabel(self.ca_widget_24)
        self.ca_label_24.setObjectName(u"ca_label_24")
        self.ca_label_24.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_24.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_24.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_24.setScaledContents(True)
        self.ca_widget_20 = QWidget(self.widget_3)
        self.ca_widget_20.setObjectName(u"ca_widget_20")
        self.ca_widget_20.setGeometry(QRect(245, 414, 240, 138))
        self.ca_widget_20.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_20 = QLabel(self.ca_widget_20)
        self.ca_label_20.setObjectName(u"ca_label_20")
        self.ca_label_20.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_20.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_20.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_20.setScaledContents(True)
        self.ca_widget_22 = QWidget(self.widget_3)
        self.ca_widget_22.setObjectName(u"ca_widget_22")
        self.ca_widget_22.setGeometry(QRect(725, 414, 240, 138))
        self.ca_widget_22.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_22 = QLabel(self.ca_widget_22)
        self.ca_label_22.setObjectName(u"ca_label_22")
        self.ca_label_22.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_22.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_22.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_22.setScaledContents(True)
        self.ca_widget_19 = QWidget(self.widget_3)
        self.ca_widget_19.setObjectName(u"ca_widget_19")
        self.ca_widget_19.setGeometry(QRect(5, 414, 240, 138))
        self.ca_widget_19.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_19 = QLabel(self.ca_widget_19)
        self.ca_label_19.setObjectName(u"ca_label_19")
        self.ca_label_19.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_19.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_19.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_19.setScaledContents(True)
        self.ca_widget_27 = QWidget(self.widget_3)
        self.ca_widget_27.setObjectName(u"ca_widget_27")
        self.ca_widget_27.setGeometry(QRect(485, 552, 240, 138))
        self.ca_widget_27.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_27 = QLabel(self.ca_widget_27)
        self.ca_label_27.setObjectName(u"ca_label_27")
        self.ca_label_27.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_27.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_27.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_27.setScaledContents(True)
        self.ca_widget_26 = QWidget(self.widget_3)
        self.ca_widget_26.setObjectName(u"ca_widget_26")
        self.ca_widget_26.setGeometry(QRect(245, 552, 240, 138))
        self.ca_widget_26.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_26 = QLabel(self.ca_widget_26)
        self.ca_label_26.setObjectName(u"ca_label_26")
        self.ca_label_26.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_26.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_26.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_26.setScaledContents(True)
        self.ca_widget_28 = QWidget(self.widget_3)
        self.ca_widget_28.setObjectName(u"ca_widget_28")
        self.ca_widget_28.setGeometry(QRect(725, 552, 240, 138))
        self.ca_widget_28.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_28 = QLabel(self.ca_widget_28)
        self.ca_label_28.setObjectName(u"ca_label_28")
        self.ca_label_28.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_28.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_28.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_28.setScaledContents(True)
        self.ca_widget_25 = QWidget(self.widget_3)
        self.ca_widget_25.setObjectName(u"ca_widget_25")
        self.ca_widget_25.setGeometry(QRect(5, 552, 240, 138))
        self.ca_widget_25.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_25 = QLabel(self.ca_widget_25)
        self.ca_label_25.setObjectName(u"ca_label_25")
        self.ca_label_25.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_25.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_25.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_25.setScaledContents(True)
        self.ca_widget_32 = QWidget(self.widget_3)
        self.ca_widget_32.setObjectName(u"ca_widget_32")
        self.ca_widget_32.setGeometry(QRect(245, 690, 240, 138))
        self.ca_widget_32.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_32 = QLabel(self.ca_widget_32)
        self.ca_label_32.setObjectName(u"ca_label_32")
        self.ca_label_32.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_32.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_32.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_32.setScaledContents(True)
        self.ca_widget_31 = QWidget(self.widget_3)
        self.ca_widget_31.setObjectName(u"ca_widget_31")
        self.ca_widget_31.setGeometry(QRect(5, 690, 240, 138))
        self.ca_widget_31.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_31 = QLabel(self.ca_widget_31)
        self.ca_label_31.setObjectName(u"ca_label_31")
        self.ca_label_31.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_31.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_31.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_31.setScaledContents(True)
        self.ca_widget_29 = QWidget(self.widget_3)
        self.ca_widget_29.setObjectName(u"ca_widget_29")
        self.ca_widget_29.setGeometry(QRect(965, 552, 240, 138))
        self.ca_widget_29.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_29 = QLabel(self.ca_widget_29)
        self.ca_label_29.setObjectName(u"ca_label_29")
        self.ca_label_29.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_29.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_29.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_29.setScaledContents(True)
        self.ca_widget_30 = QWidget(self.widget_3)
        self.ca_widget_30.setObjectName(u"ca_widget_30")
        self.ca_widget_30.setGeometry(QRect(1205, 552, 240, 138))
        self.ca_widget_30.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.ca_label_30 = QLabel(self.ca_widget_30)
        self.ca_label_30.setObjectName(u"ca_label_30")
        self.ca_label_30.setGeometry(QRect(0, 0, 240, 138))
        self.ca_label_30.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ca_label_30.setPixmap(QPixmap(u"datas/images/Adobe.png"))
        self.ca_label_30.setScaledContents(True)
        self.replayWidget = QWidget(self.widget)
        self.replayWidget.setObjectName(u"replayWidget")
        self.replayWidget.setGeometry(QRect(440, 60, 1461, 861))
        self.replayWidget.setStyleSheet(u"background-color: rgb(0, 10, 20);")
        self.label_8 = QLabel(self.replayWidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 60, 1431, 791))
        self.label_8.setStyleSheet(u"background-color: rgb(121, 121, 121);")
        self.label_8.setTextFormat(Qt.AutoText)
        self.label_8.setPixmap(QPixmap(u"datas/images/lon.jpeg"))
        self.label_8.setScaledContents(True)
        self.widget_4 = QWidget(self.replayWidget)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(10, 4, 291, 51))
        self.widget_4.setStyleSheet(u"background-color: rgb(0, 52, 63);")
        self.userLVDS_2 = QCheckBox(self.widget_4)
        self.userLVDS_2.setObjectName(u"userLVDS_2")
        self.userLVDS_2.setGeometry(QRect(230, 14, 54, 16))
        self.userLVDS_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Agency FB\";")
        self.userLVDS_2.setChecked(True)
        self.stopReplay_2 = QPushButton(self.widget_4)
        self.stopReplay_2.setObjectName(u"stopReplay_2")
        self.stopReplay_2.setGeometry(QRect(160, 4, 45, 45))
        self.stopReplay_2.setStyleSheet(u"background-color: rgba(0, 10, 20,0);")
        icon10 = QIcon()
        icon10.addFile(u"datas/images/stop.png", QSize(), QIcon.Active, QIcon.On)
        self.stopReplay_2.setIcon(icon10)
        self.stopReplay_2.setIconSize(QSize(35, 35))
        self.startReplay_2 = QPushButton(self.widget_4)
        self.startReplay_2.setObjectName(u"startReplay_2")
        self.startReplay_2.setGeometry(QRect(80, 3, 40, 45))
        self.startReplay_2.setAcceptDrops(True)
        self.startReplay_2.setAutoFillBackground(False)
        self.startReplay_2.setStyleSheet(u"background-color: rgba(0, 10, 20,0);")
        icon11 = QIcon()
        icon11.addFile(u"datas/images/play.png", QSize(), QIcon.Active, QIcon.On)
        self.startReplay_2.setIcon(icon11)
        self.startReplay_2.setIconSize(QSize(40, 40))
        self.startReplay_2.setAutoDefault(True)
        self.startReplay_2.setFlat(False)
        self.loadReplay_2 = QPushButton(self.widget_4)
        self.loadReplay_2.setObjectName(u"loadReplay_2")
        self.loadReplay_2.setGeometry(QRect(20, 6, 40, 40))
        palette1 = QPalette()
        brush9 = QBrush(QColor(0, 10, 20, 0))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush9)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush9)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush9)
        self.loadReplay_2.setPalette(palette1)
        self.loadReplay_2.setMouseTracking(True)
        self.loadReplay_2.setFocusPolicy(Qt.WheelFocus)
        self.loadReplay_2.setAcceptDrops(True)
        self.loadReplay_2.setStyleSheet(u"background-color: rgba(0, 10, 20,0);")
        icon12 = QIcon()
        icon12.addFile(u"datas/images/loadV.PNG", QSize(), QIcon.Active, QIcon.On)
        self.loadReplay_2.setIcon(icon12)
        self.loadReplay_2.setIconSize(QSize(40, 40))
        self.loadReplay_2.setProperty("tabletTracking", True)
        self.allStart = QPushButton(self.widget)
        self.allStart.setObjectName(u"allStart")
        self.allStart.setGeometry(QRect(920, 9, 120, 41))
        self.allStart.setStyleSheet(u"background-color: rgb(0, 52, 63);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 20pt \"Agency FB\";")
        icon13 = QIcon()
        icon13.addFile(u"datas/images/play.png", QSize(), QIcon.Normal, QIcon.Off)
        self.allStart.setIcon(icon13)
        self.allStart.setIconSize(QSize(111, 35))
        self.allStop = QPushButton(self.widget)
        self.allStop.setObjectName(u"allStop")
        self.allStop.setGeometry(QRect(1080, 9, 120, 41))
        self.allStop.setStyleSheet(u"background-color: rgb(0, 52, 63);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 20pt \"Agency FB\";")
        self.allStop.setInputMethodHints(Qt.ImhNoAutoUppercase)
        icon14 = QIcon()
        icon14.addFile(u"datas/images/stop.png", QSize(), QIcon.Normal, QIcon.Off)
        self.allStop.setIcon(icon14)
        self.allStop.setIconSize(QSize(111, 35))
        self.folferOpen_Bt = QPushButton(self.widget)
        self.folferOpen_Bt.setObjectName(u"folferOpen_Bt")
        self.folferOpen_Bt.setGeometry(QRect(150, 940, 121, 31))
        font4 = QFont()
        font4.setFamily(u"Agency FB")
        font4.setPointSize(15)
        font4.setBold(False)
        font4.setItalic(False)
        font4.setWeight(9)
        self.folferOpen_Bt.setFont(font4)
        self.folferOpen_Bt.setStyleSheet(u"background-color: rgb(0, 52, 63);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Agency FB\";")
        self.folferSelect_Bt = QPushButton(self.widget)
        self.folferSelect_Bt.setObjectName(u"folferSelect_Bt")
        self.folferSelect_Bt.setGeometry(QRect(30, 940, 111, 31))
        self.folferSelect_Bt.setFont(font4)
        self.folferSelect_Bt.setStyleSheet(u"background-color: rgb(0, 52, 63);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Agency FB\";")
        self.folferAddres = QLineEdit(self.widget)
        self.folferAddres.setObjectName(u"folferAddres")
        self.folferAddres.setGeometry(QRect(24, 908, 401, 21))
        self.folferAddres.setAcceptDrops(True)
        self.folferAddres.setStyleSheet(u"background-color: rgb(0, 12, 23);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"HY\uacac\uace0\ub515\";")
        self.folferAddres.setDragEnabled(True)
        self.folferAddres.setProperty("tabletTracking", False)
        self.loadmap_wg = QWidget(self.widget)
        self.loadmap_wg.setObjectName(u"loadmap_wg")
        self.loadmap_wg.setGeometry(QRect(20, 370, 411, 181))
        self.loadmap_wg.setStyleSheet(u"background-color: rgb(0, 52, 63);")
        self.loadmap = QPushButton(self.loadmap_wg)
        self.loadmap.setObjectName(u"loadmap")
        self.loadmap.setGeometry(QRect(0, 0, 411, 181))
        self.loadmap.setStyleSheet(u"background-color: rgb(10, 44, 45);")
        self.label_6 = QLabel(self.loadmap_wg)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 0, 411, 181))
        self.label_6.setPixmap(QPixmap(u"datas/images/cut_map1.png"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.loadmap_wg)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(126, 10, 161, 21))
        self.label_7.setStyleSheet(u"background-color: rgb(0, 68, 97);\n"
"font: 18pt \"Agency FB\";\n"
"color: rgb(255, 255, 255);")
        self.splash_Scr = QLabel(self.centralwidget)
        self.splash_Scr.setObjectName(u"splash_Scr")
        self.splash_Scr.setGeometry(QRect(30, 1040, 1141, 671))
        self.splash_Scr.setStyleSheet(u"background-color: rgb(56, 56, 56);\n"
"font: 75 40pt \"\ub9d1\uc740 \uace0\ub515\";\n"
"color: rgb(255, 255, 255);")
        self.functionBt_11 = QPushButton(self.centralwidget)
        self.functionBt_11.setObjectName(u"functionBt_11")
        self.functionBt_11.setGeometry(QRect(1540, 1180, 55, 48))
        font5 = QFont()
        font5.setFamily(u"\ub098\ub214\uace0\ub515 ExtraBold")
        font5.setPointSize(25)
        font5.setBold(False)
        font5.setItalic(False)
        font5.setWeight(9)
        self.functionBt_11.setFont(font5)
        self.functionBt_11.setStyleSheet(u"background-color: rgb(147, 147, 147);\n"
"font: 75 25pt \"\ub098\ub214\uace0\ub515 ExtraBold\";")
        self.stop_bt = QPushButton(self.centralwidget)
        self.stop_bt.setObjectName(u"stop_bt")
        self.stop_bt.setGeometry(QRect(1610, 1180, 55, 51))
        font6 = QFont()
        font6.setFamily(u"\ub098\ub214\uace0\ub515 ExtraBold")
        font6.setPointSize(30)
        font6.setBold(False)
        font6.setItalic(False)
        font6.setWeight(9)
        self.stop_bt.setFont(font6)
        self.stop_bt.setStyleSheet(u"background-color: rgb(147, 147, 147);\n"
"font: 75 30pt \"\ub098\ub214\uace0\ub515 ExtraBold\";")
        self.widget_9 = QWidget(self.centralwidget)
        self.widget_9.setObjectName(u"widget_9")
        self.widget_9.setEnabled(True)
        self.widget_9.setGeometry(QRect(1200, 1050, 311, 631))
        self.widget_9.setMouseTracking(False)
        self.widget_9.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.sens_label_7 = QLabel(self.widget_9)
        self.sens_label_7.setObjectName(u"sens_label_7")
        self.sens_label_7.setGeometry(QRect(81, 494, 65, 21))
        self.sens_label_7.setStyleSheet(u"font: 75 12pt \"\ub9d1\uc740 \uace0\ub515\";\n"
"color: rgb(255, 255, 255);")
        self.ip_lineEdit_7 = QLineEdit(self.widget_9)
        self.ip_lineEdit_7.setObjectName(u"ip_lineEdit_7")
        self.ip_lineEdit_7.setGeometry(QRect(152, 376, 150, 20))
        self.ip_lineEdit_7.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.foco_label_7 = QLabel(self.widget_9)
        self.foco_label_7.setObjectName(u"foco_label_7")
        self.foco_label_7.setGeometry(QRect(100, 522, 43, 21))
        self.foco_label_7.setStyleSheet(u"font: 75 12pt \"\ub9d1\uc740 \uace0\ub515\";\n"
"color: rgb(255, 255, 255);")
        self.camera_lineEdit_7 = QLineEdit(self.widget_9)
        self.camera_lineEdit_7.setObjectName(u"camera_lineEdit_7")
        self.camera_lineEdit_7.setGeometry(QRect(152, 403, 150, 20))
        self.camera_lineEdit_7.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.foco_horizontalSlider_7 = QSlider(self.widget_9)
        self.foco_horizontalSlider_7.setObjectName(u"foco_horizontalSlider_7")
        self.foco_horizontalSlider_7.setGeometry(QRect(152, 522, 150, 22))
        self.foco_horizontalSlider_7.setOrientation(Qt.Horizontal)
        self.loca_label_7 = QLabel(self.widget_9)
        self.loca_label_7.setObjectName(u"loca_label_7")
        self.loca_label_7.setGeometry(QRect(80, 430, 63, 21))
        self.loca_label_7.setStyleSheet(u"font: 75 12pt \"\ub9d1\uc740 \uace0\ub515\";\n"
"color: rgb(255, 255, 255);")
        self.sens_horizontalSlider_7 = QSlider(self.widget_9)
        self.sens_horizontalSlider_7.setObjectName(u"sens_horizontalSlider_7")
        self.sens_horizontalSlider_7.setGeometry(QRect(152, 494, 150, 22))
        self.sens_horizontalSlider_7.setOrientation(Qt.Horizontal)
        self.memo_textEdit_7 = QTextEdit(self.widget_9)
        self.memo_textEdit_7.setObjectName(u"memo_textEdit_7")
        self.memo_textEdit_7.setGeometry(QRect(152, 550, 151, 71))
        self.memo_textEdit_7.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.ip_label_7 = QLabel(self.widget_9)
        self.ip_label_7.setObjectName(u"ip_label_7")
        self.ip_label_7.setGeometry(QRect(130, 376, 16, 21))
        self.ip_label_7.setStyleSheet(u"font: 75 12pt \"\ub9d1\uc740 \uace0\ub515\";\n"
"color: rgb(255, 255, 255);")
        self.loca_lineEdit_7 = QLineEdit(self.widget_9)
        self.loca_lineEdit_7.setObjectName(u"loca_lineEdit_7")
        self.loca_lineEdit_7.setGeometry(QRect(152, 430, 150, 20))
        self.loca_lineEdit_7.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.memo_label_7 = QLabel(self.widget_9)
        self.memo_label_7.setObjectName(u"memo_label_7")
        self.memo_label_7.setGeometry(QRect(100, 550, 48, 21))
        self.memo_label_7.setStyleSheet(u"font: 75 12pt \"\ub9d1\uc740 \uace0\ub515\";\n"
"color: rgb(255, 255, 255);")
        self.zoom_label_7 = QLabel(self.widget_9)
        self.zoom_label_7.setObjectName(u"zoom_label_7")
        self.zoom_label_7.setGeometry(QRect(100, 466, 43, 21))
        self.zoom_label_7.setStyleSheet(u"font: 75 12pt \"\ub9d1\uc740 \uace0\ub515\";\n"
"color: rgb(255, 255, 255);")
        self.zoom_horizontalSlider_7 = QSlider(self.widget_9)
        self.zoom_horizontalSlider_7.setObjectName(u"zoom_horizontalSlider_7")
        self.zoom_horizontalSlider_7.setGeometry(QRect(152, 466, 150, 22))
        self.zoom_horizontalSlider_7.setOrientation(Qt.Horizontal)
        self.iconBt_7 = QPushButton(self.widget_9)
        self.iconBt_7.setObjectName(u"iconBt_7")
        self.iconBt_7.setGeometry(QRect(160, 10, 131, 131))
        self.iconBt_7.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 11pt \"Agency FB\";\n"
"font: 16pt \"Agency FB\";\n"
"image: url(:/icons/images/settingTransPb.png)\n"
"")
        icon15 = QIcon()
        icon15.addFile(u"../../../.designer/backup/datas/images/settingTransPb.png", QSize(), QIcon.Normal, QIcon.Off)
        self.iconBt_7.setIcon(icon15)
        self.iconBt_7.setIconSize(QSize(200, 200))
        self.camera__label_7 = QLabel(self.widget_9)
        self.camera__label_7.setObjectName(u"camera__label_7")
        self.camera__label_7.setGeometry(QRect(90, 403, 55, 21))
        self.camera__label_7.setStyleSheet(u"font: 75 12pt \"\ub9d1\uc740 \uace0\ub515\";\n"
"color: rgb(255, 255, 255);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1921, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.showReplay.setDefault(True)
        self.startReplay_2.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Camera List</span></p></body></html>", None))
        self.showRealtime.setText("")
        self.showReplay_2.setText("")
#if QT_CONFIG(accessibility)
        self.showReplay.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.showReplay.setText("")
#if QT_CONFIG(shortcut)
        self.showReplay.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.label_4.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Alarm &amp; File List</span></p></body></html>", None))

        __sortingEnabled = self.cmr_listWidget_5.isSortingEnabled()
        self.cmr_listWidget_5.setSortingEnabled(False)
        ___qlistwidgetitem = self.cmr_listWidget_5.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"Alaram No.1", None));
        ___qlistwidgetitem1 = self.cmr_listWidget_5.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Alaram No.2", None));
        ___qlistwidgetitem2 = self.cmr_listWidget_5.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Alaram No.3", None));
        ___qlistwidgetitem3 = self.cmr_listWidget_5.item(3)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Alaram No.4", None));
        ___qlistwidgetitem4 = self.cmr_listWidget_5.item(4)
        ___qlistwidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Alaram No.5", None));
        ___qlistwidgetitem5 = self.cmr_listWidget_5.item(5)
        ___qlistwidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Alaram No.6", None));
        ___qlistwidgetitem6 = self.cmr_listWidget_5.item(6)
        ___qlistwidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Alaram No.7", None));
        ___qlistwidgetitem7 = self.cmr_listWidget_5.item(7)
        ___qlistwidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Alaram No.8", None));
        ___qlistwidgetitem8 = self.cmr_listWidget_5.item(8)
        ___qlistwidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Alaram No.9", None));
        ___qlistwidgetitem9 = self.cmr_listWidget_5.item(9)
        ___qlistwidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem10 = self.cmr_listWidget_5.item(10)
        ___qlistwidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem11 = self.cmr_listWidget_5.item(11)
        ___qlistwidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem12 = self.cmr_listWidget_5.item(12)
        ___qlistwidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem13 = self.cmr_listWidget_5.item(13)
        ___qlistwidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem14 = self.cmr_listWidget_5.item(14)
        ___qlistwidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem15 = self.cmr_listWidget_5.item(15)
        ___qlistwidgetitem15.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem16 = self.cmr_listWidget_5.item(16)
        ___qlistwidgetitem16.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem17 = self.cmr_listWidget_5.item(17)
        ___qlistwidgetitem17.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem18 = self.cmr_listWidget_5.item(18)
        ___qlistwidgetitem18.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem19 = self.cmr_listWidget_5.item(19)
        ___qlistwidgetitem19.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem20 = self.cmr_listWidget_5.item(20)
        ___qlistwidgetitem20.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem21 = self.cmr_listWidget_5.item(21)
        ___qlistwidgetitem21.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem22 = self.cmr_listWidget_5.item(22)
        ___qlistwidgetitem22.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem23 = self.cmr_listWidget_5.item(23)
        ___qlistwidgetitem23.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem24 = self.cmr_listWidget_5.item(24)
        ___qlistwidgetitem24.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem25 = self.cmr_listWidget_5.item(25)
        ___qlistwidgetitem25.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem26 = self.cmr_listWidget_5.item(26)
        ___qlistwidgetitem26.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem27 = self.cmr_listWidget_5.item(27)
        ___qlistwidgetitem27.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem28 = self.cmr_listWidget_5.item(28)
        ___qlistwidgetitem28.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        ___qlistwidgetitem29 = self.cmr_listWidget_5.item(29)
        ___qlistwidgetitem29.setText(QCoreApplication.translate("MainWindow", u"Alaram No.10", None));
        self.cmr_listWidget_5.setSortingEnabled(__sortingEnabled)

        self.functionBt_06.setText("")
        self.functionBt_05.setText("")
        self.functionBt_04.setText("")
        self.functionBt_07.setText("")
        self.functionBt_08.setText("")
        self.functionBt_10.setText("")
        self.functionBt_09.setText("")
        self.functionBt_02.setText("")
        self.functionBt_01.setText("")
        self.functionBt_03.setText("")
        self.timeedit.setText(QCoreApplication.translate("MainWindow", u"1234-56-78 12:34:56", None))
        self.ca_label_01.setText("")
        self.ca_label_02.setText("")
        self.ca_label_03.setText("")
        self.ca_label_04.setText("")
        self.ca_label_05.setText("")
        self.ca_label_06.setText("")
        self.ca_label_09.setText("")
        self.ca_label_11.setText("")
        self.ca_label_12.setText("")
        self.ca_label_08.setText("")
        self.ca_label_10.setText("")
        self.ca_label_07.setText("")
        self.ca_label_15.setText("")
        self.ca_label_17.setText("")
        self.ca_label_18.setText("")
        self.ca_label_14.setText("")
        self.ca_label_16.setText("")
        self.ca_label_13.setText("")
        self.ca_label_21.setText("")
        self.ca_label_23.setText("")
        self.ca_label_24.setText("")
        self.ca_label_20.setText("")
        self.ca_label_22.setText("")
        self.ca_label_19.setText("")
        self.ca_label_27.setText("")
        self.ca_label_26.setText("")
        self.ca_label_28.setText("")
        self.ca_label_25.setText("")
        self.ca_label_32.setText("")
        self.ca_label_31.setText("")
        self.ca_label_29.setText("")
        self.ca_label_30.setText("")
#if QT_CONFIG(whatsthis)
        self.replayWidget.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/icons/images/AdobeStock_bg.jpeg\"/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_8.setText("")
        self.userLVDS_2.setText(QCoreApplication.translate("MainWindow", u"LVDS", None))
        self.stopReplay_2.setText("")
        self.startReplay_2.setText("")
        self.loadReplay_2.setText("")
        self.allStart.setText(QCoreApplication.translate("MainWindow", u"  START", None))
        self.allStop.setText(QCoreApplication.translate("MainWindow", u"  STOP", None))
        self.folferOpen_Bt.setText(QCoreApplication.translate("MainWindow", u"FOLDER OPEN", None))
        self.folferSelect_Bt.setText(QCoreApplication.translate("MainWindow", u"FOLDER SELECT", None))
        self.loadmap.setText("")
        self.label_6.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Camera Map</span></p></body></html>", None))
        self.splash_Scr.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600;\">Splash Screen</span></p></body></html>", None))
        self.functionBt_11.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.stop_bt.setText(QCoreApplication.translate("MainWindow", u"\u3141", None))
        self.sens_label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Sensitive</p></body></html>", None))
        self.foco_label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Focos</p></body></html>", None))
        self.loca_label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Location</p><p><br/></p></body></html>", None))
        self.ip_label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Ip</p></body></html>", None))
        self.memo_label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Memo</p></body></html>", None))
        self.zoom_label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Zoom</p></body></html>", None))
        self.iconBt_7.setText("")
        self.camera__label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Camera</p></body></html>", None))
    # retranslateUi

